//! REST API for `fs-inventory` — `axum` routes with `utoipa` `OpenAPI` docs.
// Needed for code generated by the `#[derive(OpenApi)]` macro.
#![allow(clippy::needless_for_each)]
//!
//! Routes:
//!   GET    /health              — health probe
//!   GET    /resources           — list all installed resources
//!   POST   /resources           — upsert resource
//!   GET    /resources/{id}      — get resource by id
//!   DELETE /resources/{id}      — uninstall resource
//!   GET    /services            — list services (query: ?role=iam)
//!   POST   /services            — upsert service instance
//!   GET    /status              — inventory summary

use std::sync::Arc;

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::IntoResponse,
    routing::get,
    Json, Router,
};
use serde::{Deserialize, Serialize};
use utoipa::{OpenApi, ToSchema};
use utoipa_swagger_ui::SwaggerUi;

use crate::{
    models::{InstalledResource, ServiceInstance},
    store::InventoryStore,
};

// ── Shared state ──────────────────────────────────────────────────────────────

pub type SharedStore = Arc<dyn InventoryStore>;

// ── Response / request types ──────────────────────────────────────────────────

#[derive(Debug, Serialize, ToSchema)]
pub struct HealthResponse {
    pub ok: bool,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct StatusResponse {
    pub ok: bool,
    pub resource_count: usize,
    pub service_count: usize,
}

#[derive(Debug, Serialize, ToSchema)]
pub struct ErrorResponse {
    pub error: String,
}

#[derive(Debug, Deserialize)]
pub struct RoleQuery {
    pub role: Option<String>,
}

// ── OpenAPI ───────────────────────────────────────────────────────────────────

#[allow(clippy::needless_for_each)]
#[derive(OpenApi)]
#[openapi(
    paths(
        health,
        list_resources,
        upsert_resource,
        get_resource,
        uninstall_resource,
        list_services,
        upsert_service,
        get_status,
    ),
    components(schemas(HealthResponse, StatusResponse, ErrorResponse)),
    tags((name = "inventory", description = "Local resource inventory"))
)]
pub struct ApiDoc;

// ── Router ────────────────────────────────────────────────────────────────────

/// Build the `axum` router with all routes and Swagger UI.
#[must_use = "the router must be served"]
pub fn router(store: SharedStore) -> Router {
    let api_routes = Router::new()
        .route("/health", get(health))
        .route("/status", get(get_status))
        .route("/resources", get(list_resources).post(upsert_resource))
        .route(
            "/resources/{id}",
            get(get_resource).delete(uninstall_resource),
        )
        .route("/services", get(list_services).post(upsert_service))
        .with_state(store);

    Router::new()
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()))
        .merge(api_routes)
}

// ── Handlers ──────────────────────────────────────────────────────────────────

/// Health probe — always returns `{"ok":true}` if the process is alive.
#[utoipa::path(get, path = "/health",
    responses((status = 200, description = "Service alive", body = HealthResponse))
)]
async fn health() -> Json<HealthResponse> {
    Json(HealthResponse { ok: true })
}

/// Inventory summary — resource and service counts.
#[utoipa::path(get, path = "/status",
    responses((status = 200, description = "Inventory counts", body = StatusResponse))
)]
async fn get_status(State(store): State<SharedStore>) -> impl IntoResponse {
    let resources = match store.list_resources().await {
        Ok(r) => r,
        Err(e) => {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({"error": e.to_string()})),
            )
                .into_response();
        }
    };
    let services = match store.list_services().await {
        Ok(s) => s,
        Err(e) => {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({"error": e.to_string()})),
            )
                .into_response();
        }
    };
    Json(StatusResponse {
        ok: true,
        resource_count: resources.len(),
        service_count: services.len(),
    })
    .into_response()
}

/// List all installed resources.
#[utoipa::path(get, path = "/resources",
    responses((status = 200, description = "List of installed resources", body = serde_json::Value))
)]
async fn list_resources(State(store): State<SharedStore>) -> impl IntoResponse {
    match store.list_resources().await {
        Ok(list) => Json(list).into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}

/// Upsert (install or update) a resource.
#[utoipa::path(post, path = "/resources",
    request_body(content = serde_json::Value, description = "InstalledResource JSON"),
    responses((status = 200, description = "Resource upserted"), (status = 500, body = ErrorResponse))
)]
async fn upsert_resource(
    State(store): State<SharedStore>,
    Json(body): Json<serde_json::Value>,
) -> impl IntoResponse {
    let resource: InstalledResource = match serde_json::from_value(body) {
        Ok(r) => r,
        Err(e) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(ErrorResponse {
                    error: e.to_string(),
                }),
            )
                .into_response();
        }
    };
    match store.upsert_resource(&resource).await {
        Ok(()) => StatusCode::OK.into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}

/// Get a resource by id.
#[utoipa::path(get, path = "/resources/{id}",
    params(("id" = String, Path, description = "Resource id")),
    responses(
        (status = 200, description = "Resource found", body = serde_json::Value),
        (status = 404, description = "Not found")
    )
)]
async fn get_resource(
    State(store): State<SharedStore>,
    Path(id): Path<String>,
) -> impl IntoResponse {
    match store.get_resource(&id).await {
        Ok(Some(r)) => Json(r).into_response(),
        Ok(None) => StatusCode::NOT_FOUND.into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}

/// Uninstall a resource by id.
#[utoipa::path(delete, path = "/resources/{id}",
    params(("id" = String, Path, description = "Resource id")),
    responses((status = 200, description = "Uninstalled"), (status = 404, description = "Not found"))
)]
async fn uninstall_resource(
    State(store): State<SharedStore>,
    Path(id): Path<String>,
) -> impl IntoResponse {
    match store.uninstall(&id).await {
        Ok(()) => StatusCode::OK.into_response(),
        Err(crate::error::InventoryError::NotFound { .. }) => StatusCode::NOT_FOUND.into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}

/// List service instances. Filter by role with `?role=<role-id>`.
#[utoipa::path(get, path = "/services",
    params(("role" = Option<String>, Query, description = "Filter by role id")),
    responses((status = 200, description = "List of services", body = serde_json::Value))
)]
async fn list_services(
    State(store): State<SharedStore>,
    Query(q): Query<RoleQuery>,
) -> impl IntoResponse {
    let result = match q.role {
        Some(role) => store.services_with_role(&role).await,
        None => store.list_services().await,
    };
    match result {
        Ok(list) => Json(list).into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}

/// Upsert a service instance.
#[utoipa::path(post, path = "/services",
    request_body(content = serde_json::Value, description = "ServiceInstance JSON"),
    responses((status = 200, description = "Service upserted"), (status = 500, body = ErrorResponse))
)]
async fn upsert_service(
    State(store): State<SharedStore>,
    Json(body): Json<serde_json::Value>,
) -> impl IntoResponse {
    let svc: ServiceInstance = match serde_json::from_value(body) {
        Ok(s) => s,
        Err(e) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(ErrorResponse {
                    error: e.to_string(),
                }),
            )
                .into_response();
        }
    };
    match store.upsert_service(&svc).await {
        Ok(()) => StatusCode::OK.into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(ErrorResponse {
                error: e.to_string(),
            }),
        )
            .into_response(),
    }
}
